openapi: 3.1.0
info:
  title: WHOOP GPT API
  description: API for retrieving WHOOP health data
  version: 1.0.0
servers:
  - url: https://whoopgpt-production.up.railway.app
    description: Railway deployment
paths:
  /api/recovery:
    get:
      summary: Get latest WHOOP recovery for the user
      operationId: getRecovery
      parameters:
        - name: token_id
          in: query
          description: Authentication token ID
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Recovery data
          content:
            application/json:
              schema:
                type: object
                properties:
                  date:
                    type: string
                    description: Date of the recovery score
                  recovery_score:
                    type: integer
                    description: Overall recovery score (0-100)
                  hrv:
                    type: number
                    description: Heart Rate Variability in milliseconds
                  rhr:
                    type: number
                    description: Resting Heart Rate in beats per minute
                  sleep_quality:
                    type: number
                    description: Sleep quality score (0-100)
                  user_status:
                    type: string
                    description: Status of the user
        "401":
          description: Authentication required
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  auth_required:
                    type: boolean
                  auth_url:
                    type: string
  /api/sleep:
    get:
      summary: Get latest WHOOP sleep data for the user
      operationId: getSleep
      parameters:
        - name: token_id
          in: query
          description: Authentication token ID
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Sleep data
          content:
            application/json:
              schema:
                type: object
                properties:
                  date:
                    type: string
                    description: Date of the sleep record
                  score:
                    type: integer
                    description: Overall sleep score (0-100)
                  total_duration_minutes:
                    type: integer
                    description: Total sleep duration in minutes
                  efficiency:
                    type: number
                    description: Sleep efficiency percentage
                  disturbances:
                    type: integer
                    description: Number of sleep disturbances
                  deep_sleep_minutes:
                    type: integer
                    description: Time spent in deep sleep (minutes)
                  rem_sleep_minutes:
                    type: integer
                    description: Time spent in REM sleep (minutes)
                  light_sleep_minutes:
                    type: integer
                    description: Time spent in light sleep (minutes)
        "401":
          description: Authentication required
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  auth_required:
                    type: boolean
                  auth_url:
                    type: string
  /api/profile:
    get:
      summary: Get WHOOP user profile
      operationId: getProfile
      parameters:
        - name: token_id
          in: query
          description: Authentication token ID
          required: false
          schema:
            type: string
      responses:
        "200":
          description: User profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  first_name:
                    type: string
                    description: User's first name
                  last_name:
                    type: string
                    description: User's last name
                  email:
                    type: string
                    description: User's email address
        "401":
          description: Authentication required
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  auth_required:
                    type: boolean
                  auth_url:
                    type: string
  /auth:
    get:
      summary: Initiate WHOOP OAuth flow
      operationId: startAuth
      responses:
        "302":
          description: Redirect to WHOOP authorization page
  /logout:
    get:
      summary: Logout and clear session
      operationId: logout
      parameters:
        - name: token_id
          in: query
          description: Authentication token ID
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Successfully logged out
          content:
            text/plain:
              schema:
                type: string
